### ISSUE TITLE
Specify version in defco components

### ISSUE THREAD

**Issue by LittleHelicase** [BuggyOrg/lisgy#16] opened 2016-08-10 12:45 UTC
I would like to specify a version in a `defco_` component like this:

```
(defco c [d] (math/add 1 d) {:version "1.1.1"})
```

**Comment by leMaik** [comment] 2016-08-10 13:24
My variable was called `x` instead of `d`, but otherwise this is an exact duplicate of #14. :smile:

**Closed by leMaik** 2016-08-10 13:24 UTC
